### PR TITLE
Added individual strike removal to Admin Console

### PR DESCRIPTION
**Pull request by HilbertGilbertson**
Perhaps not perfect but it does the trick, while also avoiding page reloads. A bit of a pain, as the strikes aren't indexed in the db. Accomplished nevertheless.

### CODE REVIEW

**Comment by KingDGrizzle** [comment]
In fact, strikes are saved under serverDocument.users.id.strikes I think, or basically thats the path to them

**Comment by HilbertGilbertson** [comment]
Yes, and if you look at the code in the context of the files you'll see that's what is being used.

**Comment by KingDGrizzle** [comment]
I'll have to test them :P

Will mark merge-ready after tests

**Comment by HilbertGilbertson** [comment]
Works fine.



Operates without page refresh (although refreshes the page if removing *all* strikes for a particular user).

Unless anyone has suggestions, this can indeed be merged.

**Pull request merged**
