### PR TITLE
Fix for public AFK command

### PR DESCRIPTION
**Pull request by probwebdev**
Fix for public AFK command #127

### CODE REVIEW

**Review by vladfrangu — COMMENTED** [review]
Other than the formatting that I keep breaking, looks good! But doesn't this remove the per-server AFK message?

**Comment by rgiyf** [comment]
i think you're right i will look into it

**Comment by rgiyf** [comment]
Even if bluebird is superior to native Promise implementation seems that it need serious rewrite. We could stick with native nodejs promises(at least for now)

**Review by vladfrangu — APPROVED** [review]
For the fix for the AFK command, I approve.

As for the Promise, I'd have to test it.

**Pull request merged**
