### PR TITLE
Update Modules/Updater.js

### PR DESCRIPTION
**Pull request by vitalkanev**
This pull request will fix the spelling of the `GitHub` in the `Line 30`. I don't know why, but :eyes:

_I don't guess why doing pull request in `development` becuase 1 another commit (Not owned by me)_

### CODE REVIEW

**Comment by KingDGrizzle** [comment]
This could probs go in #184 , but lets wait for @GilbertGobbels opinion

**Comment by KingDGrizzle** [comment]
40c16f821621ed132141816f978d4e5929bd15b2 should be what you wanted 😄

**Comment by ffxhand** [comment]
@KingDGrizzle Close this now?

**Comment by KingDGrizzle** [comment]
I mark this issue / pull request as closed. If you have anything against this, ping me.

_This is an semi-automated reply using the Saved Replies function_

## Why did I take this decision?

I'm closing this issue, not cause of it being insignificant, but because it has been added to the v4.0.2 PR (see #184 )

**Pull request closed without merging**
