### PR TITLE
WebServer.js: Fixed interval tooltip in extension galley

### PR DESCRIPTION
**Pull request by Blazeflack**
It was displaying a date instead of the actual interval

### CODE REVIEW

**Comment by Blazeflack** [comment]
Perhaps the code should be changed further to display hours instead of minutes when appropriate (or display both hours and minutes).

**Comment by Blazeflack** [comment]
To display both hours and minutes I think this would work:
```
typeDescription = `Interval: ${moment.duration(galleryDocument.interval).hours()} hours and ${moment.duration(galleryDocument.interval).minutes()} minutes`;
```

**Comment by Blazeflack** [comment]
To get the interval as both hours and minutes, I think the following could work:

```
let interval = moment.duration(galleryDocument.interval)
```

```
typeDescription = `Interval: ${interval.hours()} hours and ${interval.minutes()} minutes`;
```

**Comment by GilbertGobbels** [comment]
Good, however, may be better fitted in the development branch before going to master. Can you make a new PR that points at the development branch?

**Pull request closed without merging**
