### PR TITLE
Ability to DnD in the maintainer console

### PR DESCRIPTION
**Pull request by TTtie**
Actually Discord allows bots setting their status to DnD, so why not?

### CODE REVIEW

**Comment by JjTheHusky** [comment]
Erm, did you test this before? It doesn't work
`ReferenceError: /root/HuskyBot/Web/views/pages/maintainer-bot-user.ejs:56
    54|                                                                                                 <option value="online"<%= bot_user.status=="online" ? " selected" : "" %>>Online</option>
    55|                                                                                                 <option value="idle"<%= bot_user.status=="idle" ? " selected" : "" %>>Idle</option>
 >> 56|                                                                                                 <option value="dnd"<%= bot.user.status=="dnd" ? " selected" : ""%>>Do Not Disturb</option>
    57|                                                                                                 <option value="offline"<%= bot_user.status=="offline" ? " selected" : "" %>>Invisible</option>
    58|                                                                                         </select>
    59|                                                                                 </span>

bot is not defined
    at eval (eval at compile (/root/HuskyBot/node_modules/ejs/lib/ejs.js:524:12), <anonymous>:227:26)
    at returnedFn (/root/HuskyBot/node_modules/ejs/lib/ejs.js:555:17)
    at tryHandleCache (/root/HuskyBot/node_modules/ejs/lib/ejs.js:203:34)
    at View.exports.renderFile [as engine] (/root/HuskyBot/node_modules/ejs/lib/ejs.js:412:10)
    at View.render (/root/HuskyBot/node_modules/express/lib/view.js:128:8)
    at tryRender (/root/HuskyBot/node_modules/express/lib/application.js:640:10)
    at Function.render (/root/HuskyBot/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/root/HuskyBot/node_modules/express/lib/response.js:966:7)
    at checkAuth (/root/HuskyBot/Web/WebServer.js:3764:8)
    at checkAuth (/root/HuskyBot/Web/WebServer.js:699:7)
    at app.get (/root/HuskyBot/Web/WebServer.js:3762:3)
    at Layer.handle [as handle_request] (/root/HuskyBot/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/HuskyBot/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/HuskyBot/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/HuskyBot/node_modules/express/lib/router/layer.js:95:5)
    at /root/HuskyBot/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/root/HuskyBot/node_modules/express/lib/router/index.js:335:12)
    at next (/root/HuskyBot/node_modules/express/lib/router/index.js:275:10)
    at requireHTTPS (/root/HuskyBot/Web/WebServer.js:184:5)
    at Layer.handle [as handle_request] (/root/HuskyBot/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/HuskyBot/node_modules/express/lib/router/index.js:317:13)
    at /root/HuskyBot/node_modules/express/lib/router/index.js:284:7
`

**Comment by KingDGrizzle** [comment]
Tttie, check your PR again, its bot_user not bot.user

**Comment by TTtie** [comment]
smh

**Comment by TTtie** [comment]
there @KingDGrizzle

**Comment by TTtie** [comment]
my logic 
img

**Comment by JjTheHusky** [comment]
Tested and it works.
Duno why anyone would use this lol.

**Pull request merged**
