### PR TITLE
Fixed anime command

### LINKED ISSUE #132: [Issue] Anime command no longer working
https://hastebin.com/tihaqabapu.pas
Causes bot to crash.
Someone said the endpoint changed, however, I have no clue. http://docs.kitsu17.apiary.io/#

This was tested on Aurora bot and confirmed.

### PR DESCRIPTION
**Pull request by Blazeflack**
data.attributes.averageRating is now being served as string instead of number, so just convert it to a number before trying to use .toFixed on it.

This fixes #132

### CODE REVIEW

**Comment by KingDGrizzle** [comment]
Unfortunately, thats not how it works either. It returns a number between 0 and 100, not 0 to 5, which makes me wonder which variant is correct: the wiki one or the result one

As such, till they reply, this doesn't *fully* fix it

**Comment by Blazeflack** [comment]
Oh you're right, the rating is off. Well at least the command is functional now. If they continue to serve it as a value between 0 and 100 we can always just divide it by 20 to get the desired format.

**Comment by KingDGrizzle** [comment]
Or replace the /5 with `%`, which seems to be the percentage of likes

**Comment by Blazeflack** [comment]
That would work too. Personally I would expect a rating to be in the X/Y format. There are outliers like rotten tomatoes which use % based rating though.

**Comment by KingDGrizzle** [comment]
Seems like everything now returns percentages instead of 0 / 5 results

**Comment by Blazeflack** [comment]
Let's stick with that then.

**Comment by KingDGrizzle** [comment]
Reviving this, I will aswell work on a new version of the anime command with embeds and such. As such, we'll merge this, BUT it will get overwritten soon.

**Pull request merged**
