### PR TITLE
Replace all "?svrid=" links with the new inline variant

### PR DESCRIPTION
**Pull request by wasdennnoch**
**Please describe the changes this PR makes and why it should be merged:**

Fixes the stop buttons not doing anything due to a 404 (path `dashboard/xyz/other/ongoing-activities?svrid=xyz` now redirects to `dashboard/xyz/xyz/other/ongoing-activities` which obvioulsy 404s).
**UPDATE**: See title essentially. The same bug as described above also occurred on many other pages so I just updated everything to the new schema,

**What does this PR do:**
- [ ] This PR changes internal functions, modules and/or utilities
  - [ ] This PR modifies the Extension API
- [ ] This PR modifies commands
  - [ ] This PR changes command functions
  - [ ] This PR changes metadata for the command, updated in `commands.js`
  - [ ] This PR removes and/or adds commands
- [x] This PR modifies Web processing and/or content
  - [x] This PR modifies static/ejs content
  - [ ] This PR modifies request processing (endpoint functions)
  - [ ] This PR modifies paths to existing resources
- [ ] This PR **only** includes non-code changes, like changes to default configurations, README, typos, etc.

### CODE REVIEW

**Comment by wasdennnoch** [comment]
Hold on, I found the same bug on a few other pages, will include them here as well.

**Comment by wasdennnoch** [comment]
Since apparently Gilbert is redoing literally everything web-related including ejs...

**Comment by wasdennnoch** [comment]
Vlad can't decide on what to think so I've just pushed the changes :mm:

This patch now replaces (almost) all "?svrid=x" with the new inline variant. There now are only 2 occurrences left of which I am not completely sure about how to replace them.
**EDIT**: Only one occurrence left which is in `/userlist` but the WebServer path handler manually asks for that query so it's required to leave that as it is.

**Review by vladfrangu — APPROVED** [review]
While I approve of this change, Gilbert is the last one to accept this

**Comment by Gilbert142** [comment]
I am not planning on redoing ejs files in my rewrite, and routes will stay the same; this PR is good to go!

**Pull request merged**
