### PR TITLE
Make filter in extensions optional

### PR DESCRIPTION
**Pull request by TTtie**
my bad, sorry

**this applies to extensions only**

### CODE REVIEW

**Comment by vladfrangu** [comment]
So thats why bot.awaitMessage was broken..

Thx ttie

**Review by vladfrangu — APPROVED** [review]
👌

**Comment by TTtie** [comment]
should work, I tested it from a browser debugger

**Comment by TTtie** [comment]
codacy i swear

**Comment by TTtie** [comment]
@KingDGrizzle You know this PR is fix for extensions only?

**Comment by vladfrangu** [comment]
yeah? why?

**Comment by TTtie** [comment]
because i make QUALITY code that I always forget to CommonSenseLint

**Comment by vladfrangu** [comment]
LMAO

**Comment by TTtie** [comment]
I said it is quality 
picc

**Pull request merged**
