### PR TITLE
♻️ Turn Wasdennnoch's forEach into a reduce

### PR DESCRIPTION
**Pull request by TTtie**
**Please describe the changes this PR makes and why it should be merged:**
Uses a much better method.
**What does this PR do:**
- [ ] This PR changes internal functions, modules and/or utilities
  - [ ] This PR modifies the Extension API
- [x] This PR modifies commands
  - [x] This PR changes command functions
  - [ ] This PR changes metadata for the command, updated in `commands.js`
  - [ ] This PR removes and/or adds commands
- [ ] This PR modifies Web processing and/or content
  - [ ] This PR modifies static/ejs content
  - [ ] This PR modifies request processing (endpoint functions)
  - [ ] This PR modifies paths to existing resources
- [ ] This PR **only** includes non-code changes, like changes to default configurations, README, typos, etc.

### CODE REVIEW

**Review by vladfrangu — CHANGES_REQUESTED** [review]
The reduce is in the wrong position + eslint. Please fix it.

**Comment by TTtie** [comment]
@KingDGrizzle Is it OK-ish now?

**Comment by vladfrangu** [comment]
@TTtie no. The reduce is wrong (returns NaN), and it is also in the wrong spot.

**Comment by TTtie** [comment]
No, it doesn't. The multiplication by 5 is literally used everywhere.  
Second, it is at the same spot as it was originally. @KingDGrizzle

**Comment by TTtie** [comment]
wait heck i found out it actually is

**Comment by vladfrangu** [comment]
Oh does it really not return NaN?

Oh is it really in the right place?

**Comment by TTtie** [comment]
Try using the current method ( (game time + game time 2) * 5) and let's see if everything is -273,15 °C :thinking: @KingDGrizzle

**Review by vladfrangu — APPROVED** [review]
Please do a test run to make sure the results are the same, otherwise LGTM!

**Pull request merged**
