### PR TITLE
Made a bunch of AwesomeBot's to GAwesomeBot

### PR DESCRIPTION
**Pull request by oskikiboy**
Title says it all.

### CODE REVIEW

**Review by TTtie — CHANGES_REQUESTED** [review]
Please point it to indev-4.0.2.

**Comment by vladfrangu** [comment]
I will nuke you for changing the db url. 
JK

**Comment by vladfrangu** [comment]
Also, theres a slight chance I won't accept a merge due to many things happening locally with coding, soo..
But we'll see ;)

**Comment by TTtie** [comment]
how does one nuke people @KingDGrizzle

**Comment by vladfrangu** [comment]
I have my ways @TTtie, I have my ways.

**Comment by TTtie** [comment]
~~don't you just run yelling that magic sentence and throwing a nuke~~

**Comment by vladfrangu** [comment]
~~No~~

**Review by TTtie — APPROVED** [review]

**Comment by Gilbert142** [comment]
Please rebase your edits unto the latest commits of this branch to avoid merge conflicts.

**Comment by vladfrangu** [comment]
Do we *really* need this anyways? I mean, website yes, sure, but for the ASCII art, i don't see its needs

**Pull request closed without merging**
