### PR TITLE
Fix for #171

### LINKED ISSUE #171: [Issue] Bot cannot log message deletes or message edit's correctly
Trying to do either outputs errors to the console, and does not log the messages in a specified channel.

Logs are here: https://hastebin.com/azakazexib.pas

### PR DESCRIPTION
**Pull request by TTtie**
This fixes #171.

Untested.

### CODE REVIEW

**Comment by KingDGrizzle** [comment]
Rebase to command_improvements

**Comment by KingDGrizzle** [comment]
Also, this won't work

disable_everyone is NOt an option, disableEveryone is

**Comment by TTtie** [comment]
I've changed the branch, but it will likely merge stuff from dev to your branch

**Comment by TTtie** [comment]
Will change the param after I get on the computer

**Comment by TTtie** [comment]
@KingDGrizzle changed the parameter now

**Pull request merged**
