### PR TITLE
Numerous fixes to filter handling

### PR DESCRIPTION
**Pull request by HilbertGilbertson**
As described in the two commits contained, I have fixed numerous issues with filter handling, and the filters should now work as intended.

### CODE REVIEW

**Comment by HilbertGilbertson** [comment]
Of course. Though the idea of review is that you test it too! ;)

**Comment by KingDGrizzle** [comment]
I mark this pull request as merge-ready. If you have anything against me merging it, please ping me.

_This is an automated reply using the Saved Replies function_

**Comment by KingDGrizzle** [comment]
After testing, it seems like it works.

Merge-ready

**Comment by KingDGrizzle** [comment]
Sensitivity.. is very broken. And the bugs we've faced, where first-time spam triggers twice still exist.

**Comment by HilbertGilbertson** [comment]
Perhaps this relates to problems with saving following bluebird? For me, countless tests have worked absolutely fine and shown no major problems in functionality. Equally, I know that for some reason your two test installs have shown issues.

**Comment by KingDGrizzle** [comment]
With bluebird off, it still has many issues. And the sensitivity setting seems not to be considered.

**Comment by HilbertGilbertson** [comment]
Having tested this with AuroraBot with you, I don't see where sensitivity wasn't working. When set on high, fewer messages were tolerated than on medium.

**Comment by KingDGrizzle** [comment]
*Could be dependency / database related*

I mark this pull request as merge-ready. If you have anything against me merging it, please ping me.

_This is an automated reply using the Saved Replies function_

**Comment by KingDGrizzle** [comment]
I can confirm that AuroraBot's spam filter works perfectly on most of the servers. Probably the issues happen in Aurora Community.

Thereby, this will get merged this week

**Pull request merged**
